steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/symmetric-hull-427018-q6/intracoastal-derm-app:latest', '.']

images:
- 'gcr.io/symmetric-hull-427018-q6/intracoastal-derm-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
